language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - secure: K5FHhXOQ3zkKooUw2xl/fS1h470x9sXNF+0W8Q1XPDC1wpahB/b8bJ4FPwA1F3g0WIxwujV+7vPxg3/rjxgwX+tiZaYitm/EuB61EFJzddJM2y2I40hmIN/rLw0MSgdv0EJ+YkgkHXNAZKKgpK5Bdwt/Sj/3aZSauptGfcY3XfGVAGkCR7WkBjnKBdaht9vbYR7gtVETurX5pnZKjsu1cYjN6dg1J49CRwXaMYHG1UhvYhDnsnM/HZiHCxAiRelzOFsvS9L8EaG3nn+5Nf12W7QEfIOZ/U7WNg7P1wHlyLLJAybZ+7YvQF4e16lZRSqPaf/4KNSG5xJiTZuGSRUyU7qUn/nyRRia4I18eVbhTQvjuYnkHsi3SUG11wpnAOXIj2XkBqjCqCfoSQHhYVmIZiq+c9RODWOHQaXjJ5VDQd3Go7nEZpPye7nDLYWHdRurEztdaOylejCaIYM88QZxRhMsemi9zUKxVixqzaBoKa3h6YEL/SAEbliucYKP/yeIqAXRwu5OdwFLvf6QT0XpYVcZI0nroPuWrrloMPWVAFc9QxmubvyVgx8w3It9dJINV86NlKDBgG67+gOlwcLqcVKvzRkG8TDUx4OlDKIkaYLsx9rsaRxaiKfeaokqLuO+drG0O3hejo+KbHACXolmQLIS2yncJnFskrWKUKr5Hb8=
  - secure: K2p1oGuSNAPXTHxx4PMp2fDlw4WwxVuRpLF0tuTbQqGjHKpWrTo5mvmmrP5Dmc6HQZdGkfVjSC2iFuztoWQalP1g1VXePFVss5hzLQPbpEfW0iGyF7uliPB3B/iCcnd/3S+QUakMGXTpUkyAl6A7TlTLnW3DjuKS1y6TFUxVb5VfBIClgRXGHzCME1SdiL7/yqRMobTkYFA5zRPpn1QGHrpHFHNrOBizH7piKuAEJfr29rz6JZILKJQ/Lg5aR3y+JANVckNXd4uyfIVEkqPgvFBrw61TJq9eqYnMHbkkeJC5OJyxTeE+Xn60l6KHwLXjBYJFVStXsTrcXcnafDdl4+N9cqZrWZB83S58TQTdzU+KZMGp9I4X2txVW+eVAON7VoQiHAR610lLTzKbpDbp/PM9qP8ovP+UwYloJ3qpcvyafj8X+hxca51ZOBZoxWXSX83e9cemNEuPIvnwtF9cxkZv5dGT/S155muLg/PJQ1L72neIKzbw/T90Z1kIcyWSxUD9mZ6xszxEn8ZGEfdIIKyryCZAKH+B0Y/jdbShX3g8AnIdt0yZNWyl2ScRO9foymcuO5GkelHBVP+nYfOLPYjWRJPxgEnBlEGRQ7JPqo9fjerJTu4nwIyxFl8FGvLmVf/3wqOQAI3XOjtrHdb/q1MyWy2c7EbR/KY3PIYgXlI=
