language: node_js
node_js: node
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: ZOmGnnAjlGHAO+JLPyMQrbpGcq0LAIC0FSDoxfKgiiEvn10Q5Mt5An/gp6z4jpaZ7C68U2U+6h7L5x/dCYZbzksp5vIbDPIBxJ87zX7QLcJUMc3Oh3nVp8na1ZUXe1y2mGx1wNDryYp8cxZQU3zzjYQmmXfFwTjXPeVpzyLKQriGgKecID6PfF305hqvPf5IzbJaK0FnjpLR5HSWpHI0A6y9DoFTjg1erUj4cSgmVRk/HUWb6Of3ayYbNkU9qDvhDeZ9VaqI/yO/5WGle8MYtlTTSxoH1UGkyuvEjxbow2UNoSZDxOmFughdKlUcLoXqM+eB47quqlUo2GPkKPMOvWh6plQ2FDXcUaamG+mtcGv9O2CJHQ/ZD4ctd2Pad5KCuHWcneOOuV90hGoE6cAsKL2yh0VPJFOa2fXOr9uJMf3OjmblksaEROwirsSZXFNA2/OXZjJIeC48Nwkc3pKpyIQ3lXd8a5uS1Pau70NxpAd1Mk73nf2vwG95RzgN0nACvH2nzBe/YxOORpT2PEAgUAyqghbAd6Vtg3a9W4qnP7FeBjIBZhFzaLGGyF6LVcVHK8shuukLQVMkCBN0CV6FFS8GWK4Kj/njmYFnWbFw72PzyaNZD0QbW2WNAH1Xh9K7aHzSOU6wC1yPtCMBlQvULQMoaXHt/W6pCv5gpMeybLk=
